project:
  type: book
  output-dir: docs

book:
  title: "A tidyverse user's guide to polars library"
  author: "An Chu"
  date: "2/4/2024"
  keyword: polars, python, dataframe
  url: https://chuvanan.github.io/cookbook-python-polars/
  repo-branch: main
  repo-url: https://github.com/chuvanan/cookbook-python-polars
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  page-navigation: true
  sidebar:
    logo: polars.jpg
    search: true
  chapters:
    - index.qmd
    - first_steps.qmd
    - data_manipulation.qmd
    - import_export.qmd
    - lazy_execution.qmd
    - benchmarking.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: solar
    code-fold: false
    monofont: Fira Mono
    css: custom.css
  pdf:
    documentclass: scrreprt
filters:
  - line-highlight



