# Summary & references {.unnumbered}

## Summary

* Zen of polars (a.k.a. the polars design principles). If you're into tidyverse, you might find the polars API design guideline familiar with [tidy design principles](https://design.tidyverse.org/)


|         - readability over saving keystrokes
|         - explicit over implicit
|         - aim for a single return dtype per expression
|         - API should nudge to fast code
|         - pure over in-place
|         - undersore over concatenated words
|         - minimize ambiguity

## References

Here is a compilation of resources, including talks, articles, blogs and tutorials, that I studied in crafting this book.

* Must watch: [Ritchie Vink's (author of polars) keynote at EuroSciPy 2023](https://www.youtube.com/watch?v=GTVm3QyJ-3I&t=43s)

* [Polars user guide](https://docs.pola.rs/)

* [Modern polars](https://kevinheavey.github.io/modern-polars/)

* [Cookbook polars for R](https://ddotta.github.io/cookbook-rpolars/)

* [Python's polars API reference](https://docs.pola.rs/py-polars/html/reference/index.html)

* [Practical business Python - Introduction to polars](https://pbpython.com/polars-intro.html)

* [Real Python - Python polars: A lightning-fast DataFrame libray](https://realpython.com/polars-python/)

* [A bird's eye view of polars](https://pola.rs/posts/polars_birds_eye_view/)

* [Awesome polars - A curated list of polars docs, talks, tools, examples and articles](https://ddotta.github.io/awesome-polars/)